imports_granularity = "Crate"
fn_single_line = true
format_strings = true
match_block_trailing_comma = true
newline_style = "Unix"
wrap_comments = true
max_width = 125
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
